#define ERRO_HEADER "[ERRO]"
#define INFO_HEADER "[INFO]"

// Info
#define EMPTY_COMMAND INFO_HEADER " Comando vazio.\n"
#define LOGIN_SUCCESSS INFO_HEADER " Login efetuado com sucesso!\n"
#define NO_TOPICS INFO_HEADER " Ainda nao existem topicos!!\n"
#define USER_REMOVED INFO_HEADER " Fostes expulso da plataforma!!\n"
#define USER_REMOVED_SPECIFIC INFO_HEADER " O utilizador '%s' foi expulso da plataforma.\n"
#define USER_NOT_FOUND INFO_HEADER " O utilizador '%s' não foi encontrado.\n"
#define USER_REMOVED_SUCCESS INFO_HEADER " O utilizador '%s' foi removido com sucesso.\n"
#define NO_USERS_CONNECTED INFO_HEADER " Nenhum utilizador conectado ate ao momento.\n"
#define EXITING INFO_HEADER " A sair...\n"
#define TOPIC_NOT_FOUND INFO_HEADER " O topico %s nao foi encontrado.\n"
#define MANAGER_SHUTDOWN INFO_HEADER " O manager foi encerrado\n"
#define TOPIC_LOCKED_SUCCESS INFO_HEADER " O topico %s foi bloqueado com sucesso.\n"
#define TOPIC_UNLOCKED_SUCCESS INFO_HEADER " O topico %s foi desbloqueado com sucesso.\n"
// Error
#define INVALID_ARGS_FEED ERRO_HEADER " Numero de argumentos invalidos. Sintaxe: ./feed <nome>\n" 
#define INVALID_ARGS_MANA ERRO_HEADER " Numero de argumentos invalidos. Sintaxe: ./manager\n" 
#define MAX_USERS_REACHED ERRO_HEADER " Numero maximo de utilizadores atingido.\n"
#define SYNTAX_ERROR_TOPICS ERRO_HEADER " Erro de sintaxe. Sintaxe: topics\n"
#define SYNTAX_ERROR_MSG ERRO_HEADER " Erro de sintaxe. Sintaxe: msg <topico> <duracao> <mensagem>\n"
#define SYNTAX_ERROR_SUBSCRIBE ERRO_HEADER " Erro de sintaxe. Sintaxe: subscribe <topico>\n"
#define SYNTAX_ERROR_UNSUBSCRIBE ERRO_HEADER " Erro de sintaxe. Sintaxe: unsubscribe <topico>\n"
#define SYNTAX_ERROR_USERS ERRO_HEADER " Erro de sintaxe. Sintaxe: users\n"
#define SYNTAX_ERROR_HELP ERRO_HEADER " Erro de sintaxe. Sintaxe: help\n"
#define SYNTAX_ERROR_REMOVE_USER ERRO_HEADER " Erro de sintaxe. Sintaxe: remove <nome>\n"
#define TOPIC_LENGTH_ERROR ERRO_HEADER " O topico nao pode ter mais de 20 caracteres.\n"
#define MESSAGE_LENGTH_ERROR ERRO_HEADER " A mensagem nao pode ter mais de 300 caracteres.\n"
#define INVALID_COMMAND ERRO_HEADER " Comando invalido.\n"
#define ERROR_READING_COMMAND ERRO_HEADER " Erro ao ler o comando.\n"
#define MANAGER_ALREADY_RUNNING ERRO_HEADER " Ja existe um manager em funcionamento.\n"
#define MANAGER_NOT_RUNNING ERRO_HEADER " Nao existe um manager em funcionamento.\n"
#define ERROR_CREATING_MONITOR_THREAD ERRO_HEADER " Erro ao criar thread de monitoramento.\n"
#define ERROR_OPENING_MANAGER_PIPE ERRO_HEADER " Erro ao abrir MANAGER_PIPE.\n"
#define ERROR_OPENING_FEED_PIPE ERRO_HEADER " Erro ao abrir FEED_PIPE.\n"
#define ERROR_CREATING_THREAD ERRO_HEADER " Erro ao criar a thread.\n"
#define USERNAME_ALREADY_EXISTS ERRO_HEADER " Nome de user já existe!!\n"
#define ERROR_CREATING_RESPONSE_THREAD ERRO_HEADER " Erro ao criar thread de resposta.\n"
#define ERROR_CREATING_MANAGER_PIPE ERRO_HEADER " Erro ao criar MANAGER_PIPE.\n"
#define ERROR_CREATING_FEED_PIPE ERRO_HEADER " Erro ao criar FEED_PIPE.\n"
#define SYNTAX_ERROR_SHOW ERRO_HEADER " Erro de sintaxe. Sintaxe: show <topico>\n"
#define SYNTAX_ERROR_LOCK ERRO_HEADER " Erro de sintaxe. Sintaxe: lock <topico>\n"
#define SYNTAX_ERROR_UNLOCK ERRO_HEADER " Erro de sintaxe. Sintaxe: unlock <topico>\n"
#define SYNTAX_ERROR_CLOSE ERRO_HEADER " Erro de sintaxe. Sintaxe: close\n"
#define TOPIC_ALREADY_LOCKED ERRO_HEADER " O topico %s ja se encontra bloqueado.\n"
#define TOPIC_ALREADY_UNLOCKED ERRO_HEADER " O topico %s ja se encontra desbloqueado.\n"
#define SYNTAX_ERROR_CLEAR ERRO_HEADER " Erro de sintaxe. Sintaxe: clear\n"
#define DURATION_ERROR ERRO_HEADER " A duracao tem de ser um numero inteiro.\n"
