#define ERRO_HEADER "[ERRO]"
#define INFO_HEADER "[INFO]"
//Info
#define EMPTY_COMMAND INFO_HEADER " Comando vazio.\n"
//Error
#define INVALID_ARGS_FEED ERRO_HEADER " Numero de argumentos invalidos. Sintaxe: ./feed <nome>\n" 
#define INVALID_ARGS_MANA ERRO_HEADER " Numero de argumentos invalidos. Sintaxe: ./manager\n" 
#define MAX_USERS_REACHED ERRO_HEADER " Numero maximo de utilizadores atingido.\n"
#define SYNTAX_ERROR_TOPICS ERRO_HEADER " Erro de sintaxe. Sintaxe: topics\n"
#define SYNTAX_ERROR_MSG ERRO_HEADER " Erro de sintaxe. Sintaxe: msg <topico> <duracao> <mensagem>\n"
#define SYNTAX_ERROR_SUBCRIBE ERRO_HEADER " Erro de sintaxe. Sintaxe: subscribe <topico>\n"
#define SYNTAX_ERROR_UNSUBCRIBE ERRO_HEADER " Erro de sintaxe. Sintaxe: unsubscribe <topico>\n"
#define SYNTAX_ERROR_HELP ERRO_HEADER " Erro de sintaxe. Sintaxe: help\n"
#define TOPIC_LENGTH_ERROR ERRO_HEADER " O topico nao pode ter mais de 20 caracteres.\n"
#define MESSAGE_LENGTH_ERROR ERRO_HEADER " A mensagem nao pode ter mais de 300 caracteres.\n"
#define INVALID_COMMAND ERRO_HEADER " Comando invalido.\n"
#define ERROR_READING_COMMAND ERRO_HEADER " Erro ao ler o comando.\n"
#define MANAGER_ALREADY_RUNNING ERRO_HEADER " Ja existe um manager em funcionamento.\n"
#define MANAGER_NOT_RUNNING ERRO_HEADER " Nao existe um manager em funcionamento. \n"
#define ERROR_CREATING_MONITOR_THREAD ERRO_HEADER " Erro ao criar thread de monitoramento.\n"
#define ERROR_OPENING_MANAGER_PIPE ERRO_HEADER " Erro ao abrir MANAGER_PIPE.\n"